// src/handlers/home_handler.zig
const std = @import("std");
const core = @import("core");
const RequestContext = core.RequestContext;
const Response = core.Response;
const Handler = core.Handler;

title: []const u8,
handler: Handler, // 👈 内部包含 Handler 类型
allocator: std.mem.Allocator,

// 🚨 必须用 create 返回指针，不能用 init 返回值
pub fn create(allocator: std.mem.Allocator, title: []const u8) !*@This() {
    const ptr = try allocator.create(@This());
    ptr.* = .{
        .allocator = allocator,
        .title = title,
        .handler = undefined, // 临时占位
    };
    // 🚨 指针地址固定后，才能绑定 VTable
    ptr.handler = Handler.init(@This(), ptr);
    return ptr;
}

/// 这个方法会被 VTable 自动调用
pub fn handle(self: *@This(), ctx: *RequestContext, res: *Response) !void {
    _ = ctx;
    // 因为 title 是动态的，所以需要在运行时格式化 HTML
    const html_content = try std.fmt.allocPrint(self.allocator,
        \\<!DOCTYPE html>
        \\<html>
        \\<head><title>{s}</title></head>
        \\<body>
        \\  <h1>Welcome to {s}!</h1>
        \\  <p>This page is generated by a Stateful VTable Handler.</p>
        \\</body>
        \\<html>
    , .{ self.title, self.title });

    // 记得释放格式化分配的内存
    defer self.allocator.free(html_content);

    try res.html(html_content);
}

// 🚨 必须提供销毁方法释放堆内存
pub fn destroy(self: *@This()) void {
    self.allocator.destroy(self);
}
